In [1]:
import numpy as np

# Scalars

In [6]:
zeroDimensions = np.array(10)

In [7]:
print(zeroDimensions)

10


In [8]:
print(type(zeroDimensions))

<class 'numpy.ndarray'>


In [21]:
print(zeroDimensions.ndim)

0


In [33]:
print(zeroDimensions)

10


# 1-D Arrays

In [11]:
oneDimensions = np.array([1,2,3], np.int16)

In [12]:
print(oneDimensions)

[1 2 3]


In [22]:
print(oneDimensions.ndim)

1


In [34]:
print(oneDimensions[1])

2


# 2-D Arrays

In [16]:
twoDimensions = np.array([[1,2,3],[4,5,6]])

In [17]:
print(twoDimensions)

[[1 2 3]
 [4 5 6]]


In [23]:
print(twoDimensions.ndim)

2


In [38]:
print(twoDimensions[1,1])

5


# 3-D Arrays

In [19]:
threeDimensions = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [20]:
print(threeDimensions)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
print(threeDimensions.ndim)

3


In [39]:
print(threeDimensions[0,1,2])

6


# Higher Dimensional Arrays

In [27]:
higherDimension = np.array([1,2,3,4], ndmin=5)

In [28]:
print(higherDimension)

[[[[[1 2 3 4]]]]]


In [29]:
print(higherDimension.ndim)

5


In [44]:
print(higherDimension[0,0,0,0,2])

3


# Slicing

### Slicing in python means taking elements from one given index to another given index.

### We pass slice instead of index like this: [start:end].

### We can also define the step, like this: [start:end:step].

### If we don't pass start its considered 0

### If we don't pass end its considered length of array in that dimension

### If we don't pass step its considered 1

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]
