# Random Function

In [1]:
import numpy as np

In [2]:
x = np.random.randint(low =0 , high = 55 , size = 10)

In [3]:
print(x)

[18  0 25  4 28 47 41 20 21  9]


In [55]:
rand = np.random.rand(3,3)

In [57]:
print(rand)

[[0.8369025  0.44916477 0.60452181]
 [0.32159179 0.38156551 0.38376118]
 [0.10915763 0.15505648 0.2713027 ]]


# Arrange Function

In [16]:
arrange = np.arange(6)

In [17]:
print(arrange)

[0 1 2 3 4 5]


# Reshape Function

In [19]:
reshape = arrange.reshape((2,3))

In [20]:
print(reshape)

[[0 1 2]
 [3 4 5]]


In [21]:
reshape = arrange.reshape((3,2))

In [22]:
print(reshape)

[[0 1]
 [2 3]
 [4 5]]


# Flatten

In [23]:
flatten = reshape.flatten()

In [24]:
print(flatten)

[0 1 2 3 4 5]


In [25]:
flatten_c = reshape.flatten('C')

In [26]:
print(flatten_c)

[0 1 2 3 4 5]


In [27]:
flatten_f = reshape.flatten('F')

In [28]:
print(flatten_f)

[0 2 4 1 3 5]


# Stack

In [29]:
x = np.array([1,2,3], dtype=np.uint8)

In [30]:
y = np.array([4,5,6], dtype=np.uint8)

In [35]:
z = np.stack((x,y), axis =0)

In [34]:
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [36]:
z = np.stack((x,y), axis =1)

In [37]:
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
z1 = np.dstack((x,y))

In [47]:
print(z1)

[[[1 4]
  [2 5]
  [3 6]]]


In [40]:
z = np.hstack((x,y))

In [41]:
print(z)

[1 2 3 4 5 6]


In [43]:
a,b,c = np.split(z,3)

In [44]:
print(a,b,c)

[1 2] [3 4] [5 6]


# Flip

In [60]:
flip = np.flip(rand, axis=1)

In [61]:
print(flip)

[[0.60452181 0.44916477 0.8369025 ]
 [0.38376118 0.38156551 0.32159179]
 [0.2713027  0.15505648 0.10915763]]


In [62]:
x = np.random.rand(4,4,4)

In [63]:
print(x)

[[[0.39413003 0.61106023 0.75868892 0.9692579 ]
  [0.08313855 0.30372338 0.51108207 0.10452868]
  [0.35637459 0.41522009 0.12046918 0.22815962]
  [0.48495097 0.39447658 0.83148103 0.32891183]]

 [[0.30443264 0.98293764 0.0166307  0.25225755]
  [0.24861995 0.23458184 0.28854652 0.59339869]
  [0.91607304 0.08734297 0.95558353 0.9527842 ]
  [0.03083207 0.48638622 0.18304482 0.72199373]]

 [[0.52656514 0.50302966 0.62785734 0.01041006]
  [0.05608175 0.21931836 0.01224136 0.30515115]
  [0.19639701 0.25937563 0.4754856  0.12083573]
  [0.39220723 0.20961036 0.52367762 0.93392458]]

 [[0.51172442 0.4800001  0.49994152 0.5487581 ]
  [0.41890764 0.06890598 0.51954493 0.83526269]
  [0.65289773 0.92340009 0.99585569 0.15834762]
  [0.71826565 0.9918426  0.69447112 0.40297384]]]


In [64]:
x = np.arange(16).reshape(4,4)

In [65]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [66]:
y = np.flip(x, axis = -1)

In [67]:
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [69]:
y = np.flipud(x)

In [70]:
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [71]:
y = np.roll(y,8)

In [72]:
print(y)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]]


# Roll

In [73]:
y = np.roll(y,8)

In [74]:
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [75]:
y = np.rot90(y)

In [76]:
print(y)

[[15 11  7  3]
 [14 10  6  2]
 [13  9  5  1]
 [12  8  4  0]]
