# Triangle Matrics 

In [1]:
import numpy as np

# Triangle

In [10]:
triangle = np.tri(5,5,k=0)

In [11]:
print(triangle)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


# Lower Triangle

In [15]:
ones = np.ones((5,5))
lower_triangle = np.tril(ones,k=0)

In [16]:
print(lower_triangle)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


# Upper Triangle

In [17]:
upper_traingle = np.triu(ones, k=0)

In [18]:
print(upper_traingle)

[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]
