# Zeros and Ones

In [2]:
import numpy as np

# Empty array

## There are two ways an empty NumPy array can be created: numpy.zeros and numpy.empty
### numpy.zeros(shape, dtype=float, order='C')
### numpy.empty(shape, dtype=float, order='C')
### numpy.empty creates an array without initializing it with any vaules it contains junk values

### numpy.empty, unlike numpy.zeros, does not set the array values to zero and, ​therefore, may be marginally faster. On the other hand, it requires the user to manually set all the values in the array ​and should be used with caution.

In [34]:
np.empty([0])

array([], dtype=float64)

In [35]:

np.empty([1])

array([7.57832764e-312])

In [36]:
np.empty([2,2], dtype = np.uint8)

array([[0, 0],
       [0, 0]], dtype=uint8)

In [37]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.37145944e-321],
       [1.37960826e-306, 8.45602760e-307, 1.11261027e-306]])

In [38]:
np.zeros([2,3], dtype = np.uint8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [39]:
np.empty([2,3], dtype=np.uint8)

array([[120,  36, 249],
       [ 29, 101,   1]], dtype=uint8)

# eye function
### numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
### The eye() method of Python numpy class returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [27]:
np.eye(3, dtype=  np.uint8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [26]:
np.eye(3,3, dtype =np.uint8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [25]:
np.eye(5, dtype =  np.uint8, k=0)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

# identity matrix
### The identity array is a square array with ones on the main diagonal. The identity() function return the identity array
### numpy.identity(n, dtype=None)

In [23]:
np.identity(4, dtype = np.uint8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=uint8)

# Ones
### numpy.ones(shape, dtype = None, order = ‘C’) : 
#### Return a new array of given shape and type, with ones.

In [40]:
np.ones((2,5,5), dtype= np.uint8)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=uint8)

# Zeros
### numpy.zeros(shape, dtype=float, order='C')

In [41]:
np.zeros((2,5,5), dtype = np.uint8)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=uint8)

# full 
### numpy.full(shape, fill_value, dtype = None, order = ‘C’)

In [45]:
np.full((3,3), fill_value = 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])