# Zeros and Ones

In [2]:
import numpy as np

# Empty array

## There are two ways an empty NumPy array can be created: numpy.zeros and numpy.empty
### numpy.zeros(shape, dtype=float, order='C')
### numpy.empty(shape, dtype=float, order='C')
### numpy.empty creates an array without initializing it with any vaules it contains junk values

### numpy.empty, unlike numpy.zeros, does not set the array values to zero and, ​therefore, may be marginally faster. On the other hand, it requires the user to manually set all the values in the array ​and should be used with caution.

In [46]:
print(np.empty([0]))
print(np.empty([1]))

[]
[1.03455024e-311]


In [45]:
print(np.empty([2,2], dtype = np.uint8))

[[0 0]
 [0 0]]


In [48]:
print(np.empty([3,3]))

[[2.22522597e-306 1.33511969e-306 1.42419666e-306]
 [9.45694587e-308 7.56590979e-307 9.79068487e-307]
 [1.39075350e-307 1.31566912e-312 2.46155009e-312]]


In [51]:
print(np.zeros([2,3], dtype = np.uint8))

[[0 0 0]
 [0 0 0]]


In [52]:
print(np.empty([2,3], dtype=np.uint8))

[[0 0 0]
 [0 0 0]]
